name: dreambooth-colossal
channels:
  - nvidia
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.10.14
  - pytorch=2.2.0=py3.10_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8
  - pip:
      - accelerate==0.29.2
      - chardet==5.2.0
      - colossalai==0.3.6
      - diffusers==0.9.0
      - huggingface-hub==0.22.2
      - pandas==2.2.2
      - safetensors==0.4.2
      - torch==2.2.2
      - torchvision==0.17.2
      - tqdm==4.66.2
      - transformers==4.25.1
